### ISSUE TITLE
[main] INFO  org.allenai.datastore.Datastore - Starting to wait on C:\Users\13838157862\.ai2\datastore\public\org.allenai.scienceparse\productionModel-v9.dat.lock

### ISSUE THREAD

**Issue by littlejiao** [allenai/science-parse#105]
![image](https://user-images.githubusercontent.com/35133062/39576110-91ab7ffa-4f0f-11e8-8860-feec7a04222a.png)

hi,
I have successfully created the jarfile for science parse but when I run the command : java -Xmx6g -jar jarfile.jar 18bc3569da037a6cb81fb081e2856b77b321c139 or even with any of my pdf papers

this error comes :
PS D:\Tools\science-parse\cli\target\scala-2.11> java -Xmx6g -jar jarfile.jar 18bc3569da037a6cb81fb081e2856b77b321c139
20:18:33.586 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
20:18:33.652 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics
20:18:33.723 [main] DEBUG c.a.internal.config.InternalConfig - Configuration override awssdk_config_override.json not found.
20:18:35.231 [main] INFO  org.allenai.datastore.Datastore - Starting to wait on C:\Users\13838157862\.ai2\datastore\public\org.allenai.scienceparse\productionModel-v9.dat.lock

It  keep stuck here and  no more run.

**Comment by dirkgr** [comment]
Please make sure that you are not running any other instance of science-parse anywhere. When you are sure of that, you can just remove the file `C:\Users\13838157862.ai2\datastore\public\org.allenai.scienceparse\productionModel-v9.dat.lock`, and try again.

**Comment by littlejiao** [comment]
Thanks！This issue has been solved.
But there is a new problem now...As follows:

D:\Tools\science-parse\cli\target\scala-2.11>java -Xmx6g -jar jarfile.jar 3.pdf
08:44:38.060 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
08:44:38.145 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics
08:44:38.226 [main] DEBUG c.a.internal.config.InternalConfig - Configuration override awssdk_config_override.json not found.
08:44:38.796 [ModelLoaderThread] INFO  org.allenai.scienceparse.Parser - Loading model from C:\Users\13838157862\.ai2\datastore\public\org.allenai.scienceparse\productionModel-v9.dat
08:44:38.796 [ForkJoinPool-1-worker-13] INFO  org.allenai.scienceparse.Parser - Loading gazetteer from C:\Users\13838157862\.ai2\datastore\public\org.allenai.scienceparse\gazetteer-v5.json
08:44:38.798 [ForkJoinPool-1-worker-13] INFO  org.allenai.scienceparse.Parser - Loading bib model from C:\Users\13838157862\.ai2\datastore\public\org.allenai.scienceparse\productionBibModel-v7.dat
08:44:38.804 [ForkJoinPool-1-worker-13] INFO  org.allenai.scienceparse.Parser - Creating gazetteer cache at C:\Users\138381~1\AppData\Local\Temp\gazetteer-v5.json-40537537.gazetteerCache.bin
08:44:49.365 [ForkJoinPool-1-worker-13] INFO  o.a.scienceparse.ParserGroundTruth - Read 1609659 papers.
08:45:35.023 [ModelLoaderThread] INFO  org.allenai.scienceparse.Parser - Loaded model from C:\Users\13838157862\.ai2\datastore\public\org.allenai.scienceparse\productionModel-v9.dat
08:45:56.236 [ForkJoinPool-1-worker-13] INFO  o.a.scienceparse.ExtractReferences - could not load kermit gazetter
Exception in thread "main" java.nio.file.FileSystemException: C:\Users\138381~1\AppData\Local\Temp\gazetteer-v5.json-40537537.gazetteerCache.bin: 另一个程序正在使用此文件，进程无法访问。

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
        at java.nio.file.Files.move(Unknown Source)
        at org.allenai.scienceparse.Parser.<init>(Parser.java:204)
        at org.allenai.scienceparse.Parser.<init>(Parser.java:143)
        at org.allenai.scienceparse.RunSP$$anonfun$main$1$$anonfun$16.apply(RunSP.scala:100)
        at org.allenai.scienceparse.RunSP$$anonfun$main$1$$anonfun$16.apply(RunSP.scala:100)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I tried to restart my computer, but it didn't work. How  should I solve this issue？

**Comment by dirkgr** [comment]
Are you sure you are not starting up two copies at the same time?

**Comment by dirkgr** [comment]
I confirmed that this is a problem on Windows. I'll see if I can get out a fix tomorrow.

**Comment by littlejiao** [comment]
Sure. I have tried to restart my computer and  retry  to run cli: java -Xmx6g -jar jarfile.jar 3.pdf. It is a shame that it still has the same issue.
Thanks for your help!

**Comment by dirkgr** [comment]
The latest version in `master` has this problem fixed.

**Comment by dirkgr** [comment]
I just pushed the fix to Maven Central as version 1.3.2. Should be all good now!

**Comment by littlejiao** [comment]
The issue has been solved. Thanks, dirkgr!
