### ISSUE TITLE
Science Parse Server - .jar not able to download model files 

### ISSUE THREAD

**Issue by amandalmia14** [allenai/science-parse#112]
I created the jar from sbt server\assembly and I got the super jar as science-parse-server-assembly-1.3.3-SNAPSHOT.jar .
As mentioned over this [link](https://github.com/allenai/science-parse/tree/master/server) I need to run 
java -Xmx6g -jar science-parse-server-assembly-1.3.3-SNAPSHOT.jar

When I am running java -Xmx6g -jar science-parse-server-assembly-1.3.3-SNAPSHOT.jar

I am getting timeout. 

```
WARN  org.allenai.datastore.Datastore: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to public.store.dev.allenai.org.s3.amazonaws.com:443 [public.store.dev.allenai.org.s3.amazonaws.com/52.218.209.58] failed: connect timed out while downloading org.allenai.scienceparse/productionModel-v9.dat. 1 retries left.
Exception in thread "main" com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to public.store.dev.allenai.org.s3.amazonaws.com:443 [public.store.dev.allenai.org.s3.amazonaws.com/54.231.184.226] failed: connect timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:5008)
	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:4982)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4231)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1398)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1259)
	at org.allenai.datastore.Datastore$$anonfun$org$allenai$datastore$Datastore$$getS3Object$1.apply(Datastore.scala:215)
	at org.allenai.datastore.Datastore$$anonfun$org$allenai$datastore$Datastore$$getS3Object$1.apply(Datastore.scala:215)
	at org.allenai.datastore.Datastore.org$allenai$datastore$Datastore$$accessDeniedWrapper(Datastore.scala:202)
	at org.allenai.datastore.Datastore.org$allenai$datastore$Datastore$$getS3Object(Datastore.scala:214)
	at org.allenai.datastore.Datastore$$anonfun$path$1.apply$mcV$sp(Datastore.scala:389)
	at org.allenai.datastore.Datastore$$anonfun$path$1.apply(Datastore.scala:387)
	at org.allenai.datastore.Datastore$$anonfun$path$1.apply(Datastore.scala:387)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:48)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.withRetries(Datastore.scala:61)
	at org.allenai.datastore.Datastore.path(Datastore.scala:386)
	at org.allenai.datastore.Datastore.filePath(Datastore.scala:343)
	at org.allenai.scienceparse.Parser.getDefaultProductionModel(Parser.java:99)
	at org.allenai.scienceparse.SPServer$$anonfun$main$1$$anonfun$9.apply(SPServer.scala:73)
	at org.allenai.scienceparse.SPServer$$anonfun$main$1$$anonfun$9.apply(SPServer.scala:73)
	at scala.Option.getOrElse(Option.scala:121)
	at org.allenai.scienceparse.SPServer$$anonfun$main$1.apply(SPServer.scala:73)
	at org.allenai.scienceparse.SPServer$$anonfun$main$1.apply(SPServer.scala:71)
	at scala.Option.foreach(Option.scala:257)
	at org.allenai.scienceparse.SPServer$.main(SPServer.scala:71)
	at org.allenai.scienceparse.SPServer.main(SPServer.scala)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to public.store.dev.allenai.org.s3.amazonaws.com:443 [public.store.dev.allenai.org.s3.amazonaws.com/54.231.184.226] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy3.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1235)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	... 42 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 57 more
INFO  org.allenai.datastore.TempCleanup$: Cleaning up file at /home/aman/.ai2/datastore/tmp/ai2-datastore-org.allenai.scienceparse%productionModel-v9.dat4393750941617116906.tmp
```

My proxy is working fine, I also tried in different system but I am getting same error. 

Appreciate your time.

**Comment by dirkgr** [comment]
I just tried this on a completely new machine, one with no prior configuration, and it worked just fine for  me. I suspect there is some issue with your network. Does it print anything else?

**Comment by dirkgr** [comment]
From your other issue, I conclude that you got this working. I'll close this issue. Let me know if you have any other problems with it!
