### ISSUE TITLE
Release 2.0.3 tries to fetch a paper from S3 instead of parsing the PDF

### ISSUE THREAD

**Issue by prhbrt** [allenai/science-parse#143]
According `--help` this should parse the provided PDF

    $ java -Xmx6g -jar science-parse-cli-assembly-2.0.3.jar 1910.05346.pdf 

However, SP tries to download a publication from S3. I tried renaming the file to `_1910.05346.pdf`, `foo.pdf` and providing an absolute path, in case a regular expression would decide where to find the pdf. None worked.

Error message:

    11:23:30.342 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal logging successfully configured to commons logger: true
    11:23:30.384 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean registered under com.amazonaws.management:type=AwsSdkMetrics
    11:23:30.433 [main] DEBUG c.a.internal.config.InternalConfig - Configuration override awssdk_config_override.json not found.
    Exception in thread "main" org.allenai.datastore.Datastore$AccessDeniedException: You don't have access to the public datastore. Check https://github.com/allenai/wiki/wiki/Getting-Started#setting-up-your-developer-environment for information about configuring your system to get access.
	    at org.allenai.datastore.Datastore.org$allenai$datastore$Datastore$$accessDeniedWrapper(Datastore.scala:205)
	    at org.allenai.datastore.Datastore.org$allenai$datastore$Datastore$$getS3Object(Datastore.scala:214)
	    at org.allenai.datastore.Datastore$$anonfun$path$1.apply$mcV$sp(Datastore.scala:389)
	    at org.allenai.datastore.Datastore$$anonfun$path$1.apply(Datastore.scala:387)
	    at org.allenai.datastore.Datastore$$anonfun$path$1.apply(Datastore.scala:387)
	    at org.allenai.datastore.Datastore.withRetries(Datastore.scala:56)
	    at org.allenai.datastore.Datastore.path(Datastore.scala:386)
	    at org.allenai.datastore.Datastore.filePath(Datastore.scala:343)
	    at org.allenai.scienceparse.Parser.getDefaultProductionModel(Parser.java:99)
	    at org.allenai.scienceparse.RunSP$$anonfun$main$1$$anonfun$11.apply(RunSP.scala:84)
	    at org.allenai.scienceparse.RunSP$$anonfun$main$1$$anonfun$11.apply(RunSP.scala:84)
	    at scala.Option.getOrElse(Option.scala:121)
	    at org.allenai.scienceparse.RunSP$$anonfun$main$1.apply(RunSP.scala:84)
	    at org.allenai.scienceparse.RunSP$$anonfun$main$1.apply(RunSP.scala:83)
	    at scala.Option.foreach(Option.scala:257)
	    at org.allenai.scienceparse.RunSP$.main(RunSP.scala:83)
	    at org.allenai.scienceparse.RunSP.main(RunSP.scala)
    Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: F43FC3F6585745DC; S3 Extended Request ID: 0YcyReyCUU0uhojQxcVukuje4m+8qqvUwfBfRrEkPvqzD6Ir6buLVehyOHC3MXMp9AOwoEB5+Ck=), S3 Extended Request ID: 0YcyReyCUU0uhojQxcVukuje4m+8qqvUwfBfRrEkPvqzD6Ir6buLVehyOHC3MXMp9AOwoEB5+Ck=
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	    at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1398)
	    at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1259)
	    at org.allenai.datastore.Datastore$$anonfun$org$allenai$datastore$Datastore$$getS3Object$1.apply(Datastore.scala:215)
	    at org.allenai.datastore.Datastore$$anonfun$org$allenai$datastore$Datastore$$getS3Object$1.apply(Datastore.scala:215)
	    at org.allenai.datastore.Datastore.org$allenai$datastore$Datastore$$accessDeniedWrapper(Datastore.scala:202)
	    ... 16 more
    11:23:33.407 [Thread-1] INFO  org.allenai.datastore.TempCleanup$ - Cleaning up file at /home/herbert/.ai2/datastore/tmp/ai2-datastore-org.allenai.scienceparse%productionModel-v9.dat52491073689376676.tmp

**Comment by rgranit** [comment]
Do you mean S3?

**Comment by prhbrt** [comment]
> Do you mean S3?

Yes, sorry. Please read the java exceptions. They suggest my pdf is being fetched from S3, instead of my file system. But as I'm not involved in developing SP, I might be wrong. Therefore please draw your own conclusion.
