### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by AakanshaDhawan** [allenai/science-parse#96]
![issue](https://user-images.githubusercontent.com/18239541/34597660-185773d8-f20e-11e7-9c38-90937b796138.png)

I have successfully created the jarfile for science parse but when I run the command : java -Xmx6g -jar jarfile.jar 18bc3569da037a6cb81fb081e2856b77b321c139 or even with any of my pdf papers

this error comes : 
C:\Users\HARSH dangerous\science-parse\cli\target\scala-2.11>java -Xmx6g -jar ja
rfile.jar triclustering.pdf
09:08:41.621 [main] DEBUG com.amazonaws.AmazonWebServiceClient - Internal loggin
g successfully configured to commons logger: true
09:08:42.309 [main] DEBUG com.amazonaws.metrics.AwsSdkMetrics - Admin mbean regi
stered under com.amazonaws.management:type=AwsSdkMetrics
09:08:42.512 [main] DEBUG c.a.internal.config.InternalConfig - Configuration ove
rride awssdk_config_override.json not found.
09:08:45.543 [ModelLoaderThread] INFO  org.allenai.scienceparse.Parser - Loading
 model from C:\Users\HARSH dangerous\.ai2\datastore\public\org.allenai.sciencepa
rse\productionModel-v9.dat
09:08:45.543 [ForkJoinPool-1-worker-5] INFO  org.allenai.scienceparse.Parser - L
oading gazetteer from C:\Users\HARSH dangerous\.ai2\datastore\public\org.allenai
.scienceparse\gazetteer-v5.json
09:08:45.575 [ForkJoinPool-1-worker-5] INFO  org.allenai.scienceparse.Parser - L
oading bib model from C:\Users\HARSH dangerous\.ai2\datastore\public\org.allenai
.scienceparse\productionBibModel-v7.dat
09:08:45.684 [ForkJoinPool-1-worker-5] INFO  org.allenai.scienceparse.Parser - C
reating gazetteer cache at C:\Users\HARSHD~1\AppData\Local\Temp\gazetteer-v5.jso
n-9ee1217b.gazetteerCache.bin
09:09:33.355 [ForkJoinPool-1-worker-5] INFO  o.a.scienceparse.ParserGroundTruth
- Read 1609659 papers.
09:19:48.757 [ForkJoinPool-1-worker-5] INFO  o.a.scienceparse.ExtractReferences
- could not load kermit gazetter
Exception in thread "main" java.util.concurrent.TimeoutException: Futures timed
out after [15 minutes]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)

        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223
)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockConte
xt.scala:53)
        at scala.concurrent.Await$.result(package.scala:116)
        at org.allenai.scienceparse.RunSP$$anonfun$main$1.apply(RunSP.scala:186)

        at org.allenai.scienceparse.RunSP$$anonfun$main$1.apply(RunSP.scala:78)
        at scala.Option.foreach(Option.scala:257)
        at org.allenai.scienceparse.RunSP$.main(RunSP.scala:78)
        at org.allenai.scienceparse.RunSP.main(RunSP.scala)

Please help me resolve this issue asap.

**Comment by dirkgr** [comment]
Sorry, I have been asleep at the wheel and didn't notice these issues. Do you still need help with this?
